version: 2
updates:
- package-ecosystem: gradle
  directory: "/Plan"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: net.fabricmc:fabric-loader
    versions:
    - ">=0, < 2"
  - dependency-name: com.djrapitops:Extension-ProtocolSupport
    versions:
    - ">= 4.a, < 5"
  - dependency-name: com.djrapitops:Extension-Tebex
    versions:
    - "> R0.6"
  - dependency-name: com.h2database:h2
    versions:
    - "> 1.4.199"
- package-ecosystem: npm
  directory: "/Plan/react/dashboard"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
