name: Suggestion
description: Feature request or an addition
body:
- type: textarea
  attributes:
    label: I would like to be able to..
    description: A clear and concise description of what you want to happen
  validations:
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: This section helps figure out why this feature is needed - What would this feature be used for? How would you use this feature?
  validations:
      required: true